// Command mcpgen validates the curated MCP surface against the upstream API
// contracts and emits the strongly typed MCP registration boundary.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

type manifest struct {
	Version int        `yaml:"version"`
	Server  serverSpec `yaml:"server"`
	Tools   []toolSpec `yaml:"tools"`
}

type serverSpec struct {
	Name        string `yaml:"name"`
	Version     string `yaml:"version"`
	Description string `yaml:"description"`
}

type toolSpec struct {
	Name        string      `yaml:"name"`
	Title       string      `yaml:"title"`
	Handler     string      `yaml:"handler"`
	Safety      string      `yaml:"safety"`
	Description string      `yaml:"description"`
	Sources     []sourceRef `yaml:"sources"`
	Input       inputSpec   `yaml:"input"`
}

type sourceRef struct {
	Spec        string `yaml:"spec"`
	OperationID string `yaml:"operation_id"`
	Channel     string `yaml:"channel"`
}

type inputSpec struct {
	Properties []propertySpec `yaml:"properties"`
}

type propertySpec struct {
	Name        string   `yaml:"name"`
	Type        string   `yaml:"type"`
	Required    bool     `yaml:"required"`
	Enum        []string `yaml:"enum"`
	Pattern     string   `yaml:"pattern"`
	Minimum     *int64   `yaml:"minimum"`
	Maximum     *int64   `yaml:"maximum"`
	Description string   `yaml:"description"`
}

type openAPIContract struct {
	Paths map[string]map[string]struct {
		OperationID string `yaml:"operationId"`
	} `yaml:"paths"`
}

type asyncAPIContract struct {
	Channels map[string]any `yaml:"channels"`
}

type templateData struct {
	Server serverSpec
	Tools  []toolView
}

type toolView struct {
	Name        string
	Title       string
	Handler     string
	Description string
	Safety      string
	Sources     []sourceRef
	Fields      []fieldView
	Required    []string
}

type fieldView struct {
	GoName     string
	GoType     string
	JSONTag    string
	JSONName   string
	JSONType   string
	Array      bool
	Enum       []string
	Pattern    string
	Minimum    *int64
	Maximum    *int64
	SchemaHelp string
}

var (
	identifierPattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	handlerPattern    = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
)

func main() {
	specPath := flag.String("spec", "specs/mcp-tools.yaml", "path to the MCP tool manifest")
	outPath := flag.String("out", "internal/gen/mcptools/tools.gen.go", "generated Go output")
	flag.Parse()

	data, err := os.ReadFile(*specPath)
	must(err)

	var spec manifest
	must(yaml.Unmarshal(data, &spec))
	must(validateManifest(*specPath, &spec))

	view := templateData{Server: spec.Server}
	for _, tool := range spec.Tools {
		tv := toolView{
			Name:        tool.Name,
			Title:       tool.Title,
			Handler:     tool.Handler,
			Description: tool.Description,
			Safety:      tool.Safety,
			Sources:     tool.Sources,
		}
		for _, property := range tool.Input.Properties {
			tv.Fields = append(tv.Fields, fieldView{
				GoName:     goName(property.Name),
				GoType:     goType(property),
				JSONTag:    jsonTag(property),
				JSONName:   property.Name,
				JSONType:   jsonType(property.Type),
				Array:      property.Type == "string_array",
				Enum:       property.Enum,
				Pattern:    property.Pattern,
				Minimum:    property.Minimum,
				Maximum:    property.Maximum,
				SchemaHelp: schemaHelp(property),
			})
			if property.Required {
				tv.Required = append(tv.Required, property.Name)
			}
		}
		view.Tools = append(view.Tools, tv)
	}

	var generated bytes.Buffer
	must(codeTemplate.Execute(&generated, view))
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		must(fmt.Errorf("format generated source: %w\n%s", err, generated.String()))
	}
	must(os.MkdirAll(filepath.Dir(*outPath), 0o755))
	must(os.WriteFile(*outPath, formatted, 0o644))
}

func validateManifest(manifestPath string, spec *manifest) error {
	if spec.Version != 1 {
		return fmt.Errorf("unsupported manifest version %d", spec.Version)
	}
	if spec.Server.Name == "" || spec.Server.Version == "" {
		return fmt.Errorf("server name and version are required")
	}

	operationSets := make(map[string]map[string]struct{})
	channelSets := make(map[string]map[string]struct{})
	specDir := filepath.Dir(manifestPath)
	for _, name := range []string{"trade", "perps"} {
		contents, err := os.ReadFile(filepath.Join(specDir, name+".yaml"))
		if err != nil {
			return err
		}
		var contract openAPIContract
		if err := yaml.Unmarshal(contents, &contract); err != nil {
			return fmt.Errorf("parse %s spec: %w", name, err)
		}
		operations := make(map[string]struct{})
		for _, pathItem := range contract.Paths {
			for method, operation := range pathItem {
				switch strings.ToLower(method) {
				case "get", "put", "post", "delete", "patch", "head", "options", "trace":
					if operation.OperationID != "" {
						operations[operation.OperationID] = struct{}{}
					}
				}
			}
		}
		operationSets[name] = operations
	}
	for _, name := range []string{"market_data_ws", "perps_ws"} {
		contents, err := os.ReadFile(filepath.Join(specDir, name+".yaml"))
		if err != nil {
			return err
		}
		var contract asyncAPIContract
		if err := yaml.Unmarshal(contents, &contract); err != nil {
			return fmt.Errorf("parse %s spec: %w", name, err)
		}
		channels := make(map[string]struct{}, len(contract.Channels))
		for channel := range contract.Channels {
			channels[channel] = struct{}{}
		}
		channelSets[name] = channels
	}

	toolNames := make(map[string]struct{})
	handlers := make(map[string]struct{})
	for _, tool := range spec.Tools {
		if !identifierPattern.MatchString(tool.Name) {
			return fmt.Errorf("invalid MCP tool name %q", tool.Name)
		}
		if !handlerPattern.MatchString(tool.Handler) {
			return fmt.Errorf("invalid handler name %q", tool.Handler)
		}
		if _, exists := toolNames[tool.Name]; exists {
			return fmt.Errorf("duplicate MCP tool name %q", tool.Name)
		}
		if _, exists := handlers[tool.Handler]; exists {
			return fmt.Errorf("duplicate handler name %q", tool.Handler)
		}
		toolNames[tool.Name] = struct{}{}
		handlers[tool.Handler] = struct{}{}
		if tool.Safety != "read" && tool.Safety != "trade" {
			return fmt.Errorf("tool %s has invalid safety class %q", tool.Name, tool.Safety)
		}
		if tool.Description == "" {
			return fmt.Errorf("tool %s requires a description", tool.Name)
		}
		if tool.Title == "" {
			return fmt.Errorf("tool %s requires a title", tool.Name)
		}

		propertyNames := make(map[string]struct{})
		for _, property := range tool.Input.Properties {
			if !identifierPattern.MatchString(property.Name) {
				return fmt.Errorf("tool %s has invalid property name %q", tool.Name, property.Name)
			}
			if _, exists := propertyNames[property.Name]; exists {
				return fmt.Errorf("tool %s has duplicate property %q", tool.Name, property.Name)
			}
			propertyNames[property.Name] = struct{}{}
			if _, ok := supportedTypes[property.Type]; !ok {
				return fmt.Errorf("tool %s property %s has unsupported type %q", tool.Name, property.Name, property.Type)
			}
			if property.Description == "" {
				return fmt.Errorf("tool %s property %s requires a description", tool.Name, property.Name)
			}
			if property.Type == "decimal" && property.Pattern == "" {
				return fmt.Errorf("tool %s decimal property %s requires an explicit JSON Schema pattern", tool.Name, property.Name)
			}
			if property.Minimum != nil && property.Maximum != nil && *property.Minimum > *property.Maximum {
				return fmt.Errorf("tool %s property %s has minimum greater than maximum", tool.Name, property.Name)
			}
		}

		for _, source := range tool.Sources {
			switch {
			case source.OperationID != "":
				operations, ok := operationSets[source.Spec]
				if !ok {
					return fmt.Errorf("tool %s references non-OpenAPI spec %q", tool.Name, source.Spec)
				}
				if _, ok := operations[source.OperationID]; !ok {
					return fmt.Errorf("tool %s references missing operation %s:%s", tool.Name, source.Spec, source.OperationID)
				}
			case source.Channel != "":
				channels, ok := channelSets[source.Spec]
				if !ok {
					return fmt.Errorf("tool %s references non-AsyncAPI spec %q", tool.Name, source.Spec)
				}
				if _, ok := channels[source.Channel]; !ok {
					return fmt.Errorf("tool %s references missing channel %s:%s", tool.Name, source.Spec, source.Channel)
				}
			default:
				return fmt.Errorf("tool %s contains an empty source reference", tool.Name)
			}
		}
	}
	return nil
}

var supportedTypes = map[string]struct{}{
	"boolean": {}, "decimal": {}, "integer": {}, "integer64": {}, "string": {}, "string_array": {},
}

func goType(property propertySpec) string {
	base := map[string]string{
		"boolean":      "bool",
		"decimal":      "string",
		"integer":      "int",
		"integer64":    "int64",
		"string":       "string",
		"string_array": "[]string",
	}[property.Type]
	if property.Required || property.Type == "string_array" {
		return base
	}
	return "*" + base
}

func jsonTag(property propertySpec) string {
	if property.Required {
		return property.Name
	}
	return property.Name + ",omitempty"
}

func jsonType(propertyType string) string {
	switch propertyType {
	case "boolean":
		return "boolean"
	case "integer", "integer64":
		return "integer"
	case "string_array":
		return "array"
	default:
		return "string"
	}
}

func schemaHelp(property propertySpec) string {
	parts := []string{property.Description}
	if len(property.Enum) > 0 {
		parts = append(parts, "Allowed values: "+strings.Join(property.Enum, ", ")+".")
	}
	if property.Minimum != nil {
		parts = append(parts, fmt.Sprintf("Minimum: %d.", *property.Minimum))
	}
	if property.Maximum != nil {
		parts = append(parts, fmt.Sprintf("Maximum: %d.", *property.Maximum))
	}
	return strings.Join(parts, " ")
}

func goName(value string) string {
	parts := strings.Split(value, "_")
	initialisms := map[string]string{"id": "ID"}
	for index, part := range parts {
		if replacement, ok := initialisms[part]; ok {
			parts[index] = replacement
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "mcpgen:", err)
		os.Exit(1)
	}
}

var codeTemplate = template.Must(template.New("generated").Parse(`// Code generated by cmd/mcpgen; DO NOT EDIT.

package mcptools

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

const (
	ServerName = {{printf "%q" .Server.Name}}
	ServerVersion = {{printf "%q" .Server.Version}}
	ServerDescription = {{printf "%q" .Server.Description}}
)

type Error struct {
	Code string ` + "`json:\"code\"`" + `
	Message string ` + "`json:\"message\"`" + `
}

type Response struct {
	Mode string ` + "`json:\"mode\"`" + `
	OK bool ` + "`json:\"ok\"`" + `
	Data map[string]any ` + "`json:\"data,omitempty\"`" + `
	Error *Error ` + "`json:\"error,omitempty\"`" + `
}

type Source struct {
	Spec string ` + "`json:\"spec\"`" + `
	OperationID string ` + "`json:\"operation_id,omitempty\"`" + `
	Channel string ` + "`json:\"channel,omitempty\"`" + `
}

var SourcesByTool = map[string][]Source{
	{{range .Tools}}{{printf "%q" .Name}}: {
		{{range .Sources}}{Spec: {{printf "%q" .Spec}}, OperationID: {{printf "%q" .OperationID}}, Channel: {{printf "%q" .Channel}}},
		{{end}}
	},
	{{end}}
}

{{range .Tools}}
// {{.Handler}}Input is generated from specs/mcp-tools.yaml.
type {{.Handler}}Input struct {
	{{range .Fields}}{{.GoName}} {{.GoType}} ` + "`json:\"{{.JSONTag}}\" jsonschema:\"{{.SchemaHelp}}\"`" + `
	{{end}}
}
{{end}}

type Handler interface {
	{{range .Tools}}{{.Handler}}(context.Context, *mcp.CallToolRequest, {{.Handler}}Input) (*mcp.CallToolResult, Response, error)
	{{end}}
}

func Register(server *mcp.Server, handler Handler) {
	{{range .Tools}}mcp.AddTool(server, &mcp.Tool{
		Name: {{printf "%q" .Name}},
		Description: {{printf "%q" .Description}},
		Annotations: &mcp.ToolAnnotations{
			Title: {{printf "%q" .Title}},
			ReadOnlyHint: {{if eq .Safety "read"}}true{{else}}false{{end}},
			DestructiveHint: boolPointer({{if eq .Safety "trade"}}true{{else}}false{{end}}),
			OpenWorldHint: boolPointer(true),
		},
		InputSchema: map[string]any{
			"type": "object",
			"additionalProperties": false,
			"properties": map[string]any{
				{{range .Fields}}{{printf "%q" .JSONName}}: map[string]any{
					"type": {{printf "%q" .JSONType}},
					"description": {{printf "%q" .SchemaHelp}},
					{{if .Array}}"items": map[string]any{"type": "string"},{{end}}
					{{if .Enum}}"enum": []string{ {{range .Enum}}{{printf "%q" .}},{{end}} },{{end}}
					{{if .Pattern}}"pattern": {{printf "%q" .Pattern}},{{end}}
					{{if .Minimum}}"minimum": {{.Minimum}},{{end}}
					{{if .Maximum}}"maximum": {{.Maximum}},{{end}}
				},{{end}}
			},
			{{if .Required}}"required": []string{ {{range .Required}}{{printf "%q" .}},{{end}} },{{end}}
		},
	}, handler.{{.Handler}})
	{{end}}
}

func boolPointer(value bool) *bool {
	return &value
}
`))
